services:
  cve-2025-29927-vuln:
    build:
      context: ./pocs/cve-2025-29927
      args:
        NEXT_VERSION: 15.2.2
        REACT_VERSION: 19.0.0
    ports:
      - "3001:3000"

  cve-2025-29927-fixed:
    build:
      context: ./pocs/cve-2025-29927
      args:
        NEXT_VERSION: 15.2.3
        REACT_VERSION: 19.0.0
    ports:
      - "3002:3000"

  cve-2026-27978-vuln:
    build:
      context: ./pocs/cve-2026-27978
      args:
        NEXT_VERSION: 16.1.6
        REACT_VERSION: 19.0.0
    ports:
      - "3003:3000"

  cve-2026-27978-fixed:
    build:
      context: ./pocs/cve-2026-27978
      args:
        NEXT_VERSION: 16.1.7
        REACT_VERSION: 19.0.0
    ports:
      - "3004:3000"

  cve-2026-29057-vuln:
    build:
      context: ./pocs/cve-2026-29057
      args:
        NEXT_VERSION: 15.5.12
        REACT_VERSION: 19.0.0
    ports:
      - "3005:3000"

  cve-2026-29057-fixed:
    build:
      context: ./pocs/cve-2026-29057
      args:
        NEXT_VERSION: 15.5.13
        REACT_VERSION: 19.0.0
    ports:
      - "3006:3000"

  next-16-image-redirect-bypass:
    build:
      context: ./pocs/next-16.2.4-image-redirect-allowlist-bypass
      args:
        NEXT_VERSION: 16.2.4
        REACT_VERSION: 19.0.0
    ports:
      - "3007:3000"

  next-16-image-local-rewrite-ssrf:
    build:
      context: ./pocs/next-16.2.4-image-local-rewrite-ssrf
      args:
        NEXT_VERSION: 16.2.4
        REACT_VERSION: 19.0.0
    ports:
      - "3008:3000"
